plugins {
	id 'org.jetbrains.kotlin.jvm' version '2.3.0'
	id 'org.jetbrains.kotlin.plugin.spring' version '2.3.0'
	id 'org.jetbrains.kotlin.plugin.jpa' version '2.3.0'
	id 'org.jetbrains.kotlin.plugin.allopen' version '2.3.0'
	id 'org.springframework.boot' version '3.5.0'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.google.protobuf' version '0.9.4'
	id 'com.diffplug.spotless' version '6.25.0'
}

group = 'com.mrmention'
version = '0.0.1-SNAPSHOT'
description = 'Nextstay mini reservation system'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-amqp'
	implementation 'com.fasterxml.jackson.module:jackson-module-kotlin'
	implementation 'org.jetbrains.kotlin:kotlin-reflect'
	runtimeOnly 'com.mysql:mysql-connector-j'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.jetbrains.kotlin:kotlin-test-junit5'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'

	implementation 'io.jsonwebtoken:jjwt-api:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.5'
	runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.5'

	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5'

	// gRPC
	implementation 'io.grpc:grpc-netty-shaded:1.68.0'
	implementation 'io.grpc:grpc-protobuf:1.68.0'
	implementation 'io.grpc:grpc-stub:1.68.0'
	implementation 'io.grpc:grpc-kotlin-stub:1.4.1'
	implementation 'com.google.protobuf:protobuf-kotlin:3.25.1'
	implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.1'
	implementation 'com.fasterxml.uuid:java-uuid-generator:5.1.0'
	compileOnly 'jakarta.annotation:jakarta.annotation-api:2.1.1'
}

sourceSets {
	main {
		proto {
			srcDir '../proto'
		}
	}
}

protobuf {
	protoc {
		artifact = "com.google.protobuf:protoc:3.25.1"
	}
	plugins {
		grpc {
			artifact = 'io.grpc:protoc-gen-grpc-java:1.68.0'
		}
		grpckt {
			artifact = 'io.grpc:protoc-gen-grpc-kotlin:1.4.1:jdk8@jar'
		}
	}
	generateProtoTasks {
		all().each { task ->
			task.plugins {
				grpc {}
				grpckt {}
			}
			task.builtins {
				kotlin {}
			}
		}
	}
}

kotlin {
	compilerOptions {
		freeCompilerArgs.addAll '-Xjsr305=strict', '-Xannotation-default-target=param-property'
	}
}

allOpen {
	annotation("jakarta.persistence.Entity")
	annotation("jakarta.persistence.MappedSuperclass")
	annotation("jakarta.persistence.Embeddable")
}

tasks.named('test') {
	useJUnitPlatform()
}

spotless {
	kotlin {
		target "**/*.kt"
		ktlint("1.4.1").editorConfigOverride([
			"ktlint_standard_max-line-length": "disabled",
			"ktlint_standard_no-wildcard-imports": "disabled",
			"ktlint_standard_value-parameter-comment": "disabled",
			"ktlint_standard_import-ordering": "disabled",
			"ktlint_standard_function-naming": "disabled",
			"ktlint_standard_property-naming": "disabled",
			"ktlint_standard_class-naming": "disabled",
			"ktlint_standard_no-multi-spaces": "disabled",
			"ktlint_standard_no-blank-line-before-rbrace": "disabled",
			"ktlint_standard_no-consecutive-blank-lines": "disabled",
			"ktlint_standard_discouraged-comment-location": "disabled",
			"ktlint_standard_parameter-list-wrapping": "disabled",
			"ktlint_standard_argument-list-wrapping": "disabled",
			"ktlint_standard_comment-spacing": "disabled",
			"ktlint_standard_trailing-comma-on-call-site": "disabled",
			"ktlint_standard_trailing-comma-on-declaration-site": "disabled",
			"ktlint_standard_filename": "disabled"
		])
		trimTrailingWhitespace()
		endWithNewline()
	}
}
